* SII Learning - Cours Git

* Installer Git

Installer git normalement en fonction de votre Systeme d'Exploitation (OS).

Puis configurer un compte git global sur la machine locale.

#+begin_src shell
git config --global user.email "<adresse@mail.com>"
git config --global user.name "<Identifiant>"
#+end_src

* Initialiser un depot

Initialise la mecanique de git dans le repertoire pour qu'il devienne un depot git.
/Un fichier cache =.git= apparait./

#+begin_src shell
git init
#+end_src

* Vers depot distant

** Ajouter des fichiers (Stage)

Ajouter un/des fichier(s) au depot pour les commit.

#+begin_src shell
git add <fichier(s)>
#+end_src

Ajouter tous les fichiers au depot pour les commit.

#+begin_src shell
git add .
#+end_src

** Preparer l'Envoi (Commit)

Preparer les fichiers a l'envoi et assigner une description.

#+begin_src shell
git commit -m "<message>"
#+end_src

** Envoyer les changements

Envoyer les modification sur le depot main distant.

#+begin_src shell
git push -u origin main
#+end_src

* Depot distant vers local

** Cloner un depot

Recuperer un depot distant non existant sur la machine locale.

#+begin_src shell
git clone <url_du_depot>
#+end_src

** Recuperer des fichiers

Recuperer des fichiers distants non existant dans le depot local.

#+begin_src shell
git fetch origin
#+end_src

** Mettre a jour le depot local

Fusion de =fetch + merge= .

Mettre a jour son depot local en se synchronisant avec les modifications distantes.

*/!\ IMPORTANT /!\*
Toute modification locale sera remplacee pour les donnees distantes.

#+begin_src shell
git pull
#+end_src

* Manipulation de branches

** Creer une branche

Creer une branche.

#+begin_src shell
git checkout -b <branche>
#+end_src

** Changer de branche

Passer d'une branche a l'autre.

#+begin_src shell
git checkout <branche>
#+end_src

** Supprimer une branche

Supprimer une branche.

#+begin_src shell
git checkout -d <branche>
#+end_src

* Monitoring

** Voir les log

Voir l'historique des commits.

#+begin_src shell
git log
#+end_src

** Voir l'etat du depot

Voir l'etat des modifications en cours sur le depot (rien, ajouts, commit a push).

#+begin_src shell
git status
#+end_src

